### ISSUE TITLE
Change URL Streaming

### ISSUE THREAD

**Issue by marcokenny** [ccrisan/motionPie#104]
is possibile to change URL Streaming ?, from control pannel i can't modify it.
Thanks
Marco

**Comment by ddyeakley** [comment]
2nd this, would be nice to change with out deleting  and re-adding...

**Comment by ccrisan** [comment]
If this issue refers to the Streaming URL box which normally reads http://motionpie_ip:8081/, it cannot be changed given the way motion daemon works.

If it refers to the URL of a previously added network camera, then the answer is no, because it's too complicated and requires too many changes to the existing code.
