### ISSUE TITLE
Ratio Issue at 2592 x 1944

### ISSUE THREAD

**Issue by GizmoRA2** [ccrisan/motionpie#348]
Ok... Lets start again
I modified https://github.com/ccrisan/motioneye/blob/master/motioneye/utils.py to add in 2592, 1944 as a resolution option and saved it into /usr/lib/python2.7/site-packages/motioneye/utils.py
I then rebooted the Raspberry Pi

When I change from 1280 x 1024 to 2592 x 1944 which is the cameras highest "native" resolution it crops all 4 sides of the image and blows it up (or only uses a limited area of the sensor and then blows it up) instead of showing at least the same area as the 1280 x 1024 image does

I'm not sure why this is happening, however I can reproduce it using motioneye in motioneyeos on a RPi B

Thanks heaps
Gizmo

**Comment by GizmoRA2** [comment]
I have just realised this maybe posted in the wrong place as it relates to motionpieos
My appologese if this is the case, as I am not sure if it is specific to motionpieos or if it is more relevant to motionpie as the underlying software

Also this is running on a RPi B if that makes any difference though I am sure it wont :)

**Comment by GizmoRA2** [comment]
1280x960 seems to yield the best results so far and works with fast network camera mode

However it would be nice to get a higher resolution at the 4:3 ratio working (taking advantage of the entire sensor)

**Comment by ccrisan** [comment]
Both the width and the height must be *modulo 16* numbers in order to work with *motion*. Cropping may occur due to using the video port instead of the still images port of the CSI camera. However I strongly suggest not using resolutions that high with motionEye(OS) as they generate way too much data for the PI to process, even at lower framerates.

More details on this matter should be found on the Raspberry PI forum.

**Comment by GizmoRA2** [comment]
Ok

I might just use stills for push notifications :)

Thanks for the quick reply
Gizmo
